# Good example - https://github.com/pathawks/pathawks.github.com/blob/master/_config.yml
# Newer Example: https://github.com/codebykat/blog/blob/master/_config.yml
#auto:       true
# destination: ./_site
#safe: true
encoding:     "utf-8"
lsi: false

destination: docs/

# Conversion
highlighter: rouge
sass:
  style: compressed

exclude: ['.gitignore', 'README.md', "Rakefile", 'ideas.md', 'misc.md']
permalink:  /:year/:month/:day/:title.html


# Site information used by the layouts and SEO
title: 'TheWorkAround'
name: TheWorkAround
url: https://theworkaround.com
tagline: 'blah blah blah'
description: 'The infinate rambelings and ideas of Brandon Hicks'
keywords: [ design, development, ruby ]

author:
  email: tarellel@gmail.com
  name: 'Brandon Hicks'
  github: tarellel
  twitter: tarellel

apis:
  google_analytics: UA-XXXXX-X
  disqus_shortname: theworkaround

# tagging - https://github.com/pattex/jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# for jekyll-assets
assets:
  # Autoprefixer
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
  # jekyll-assets
  source_maps: false
  dirname: assets
  destination: "/assets"
  compression: true
  gzip: false
  # Pathnames where to find assets relative to the root of the site.
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    #- _assets/fonts
  gzip: [ text/css, application/javascript ]
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  # image_optim for assets -> https://github.com/envygeeks/jekyll-assets#imageoptim
  plugins:
    img:
      optim: false

plugins:
    - jekyll-minifier
    - jekyll-seo-tag
    - jekyll-compress-images

jekyll-minifier:
  exclude: ['atom.xml','rss.xml','sitemap.xml'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

# used by jekyll-compress-images
imageoptim:
  pngout: false
  svgo: false
  verbose: false
compress_images:
  images_path: "img/**/*.{gif,png,jpg,jpeg,svg}"
