# Good example - https://github.com/pathawks/pathawks.github.com/blob/master/_config.yml
# Newer Example: https://github.com/codebykat/blog/blob/master/_config.yml
#auto:       true
# destination: ./_site
#safe: true
encoding:     "utf-8"
lsi: false

destination: docs/

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude: ['.gitignore', 'README.md', "Rakefile", 'ideas.md', 'misc.md']
permalink:  /:year/:month/:day/:title.html

title: 'TheWorkAround'
name: TheWorkAround
url: http://theworkaround.com
tagline: 'blah blah blah'
description: 'The infinate rambelings and ideas of Brandon Hicks'
keywords: [ design, development, ruby ]

author:
  email: tarellel@gmail.com
  name: 'Brandon Hicks'
  github: tarellel
  twitter: tarellel

apis:
  google_analytics: UA-XXXXX-X
  disqus_shortname: theworkaround

# tagging - https://github.com/pattex/jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# for jekyll-assets
assets:
  dirname: assets
  #baseurl: /assets/

  compress:
    css:  scss
    js:   uglifier

  # Pathnames where to find assets relative to the root of the site.
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    #- _assets/fonts
  gzip: [ text/css, application/javascript ]
